# Generated by Django 5.2.5 on 2025-08-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20250824_1227"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.AddField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience_years",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
