from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    RegisterView,
    PatientViewSet,
    DoctorViewSet,
    AssignmentViewSet,
    symptom_checker_view,
)

# The router automatically generates the URLs for our ViewSets
router = DefaultRouter()
router.register(r"patients", PatientViewSet, basename="patient")
router.register(r"doctors", DoctorViewSet, basename="doctor")

# This is the line that creates the /api/mappings/ URL
router.register(r"mappings", AssignmentViewSet, basename="mapping")

urlpatterns = [
    # Auth URLs
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", TokenObtainPairView.as_view(), name="auth-login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth-refresh"),

    # Symptom checker URL
    path("symptom-checker/", symptom_checker_view, name="symptom-checker"),

    # Include the URLs generated by the router (patients, doctors, mappings)
    path("", include(router.urls)),
]
